version: "3"
services:
  app:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      default:
      reverse-proxy-network:
        # aliases:
        #   - app1-container

networks:
  reverse-proxy-network:
    external: true
